substitutions:
  _IMAGE_TAG: dev-latest
  _SSH_KEYS: ""

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-backend
    entrypoint: bash
    args:
      - -c
      - |
        TEMPLATE_NAME=ongi-dev-template-${_IMAGE_TAG}
        IMAGE=asia-northeast3-docker.pkg.dev/dev-ongi-3-tier/dev-ongi-spring-repo/backend:${_IMAGE_TAG}

        gcloud compute instance-templates create-with-container $TEMPLATE_NAME \
          --machine-type=e2-medium \
          --region=asia-northeast3 \
          --boot-disk-size=20GB \
          --image-family=cos-stable \
          --image-project=cos-cloud \
          --container-image=$IMAGE \
          --container-env=SPRING_PROFILES_ACTIVE=dev \
          --metadata=ssh-keys="${_SSH_KEYS}" \
          --service-account=github-cd-builder@dev-ongi-3-tier.iam.gserviceaccount.com \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --tags=dev-backend

        gcloud compute instance-groups managed rolling-action start-update ongi-backend-mig \
          --region=asia-northeast3 \
          --version template=$TEMPLATE_NAME \
          --type proactive