spring:
  application:
    name: ongiBE

  kafka:
    bootstrap-servers: 10.1.20.16:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: be-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    root: INFO
    ongi.ongibe: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG

kafka:
  topic:
    request:
      embedding : "album.ai.embedding.request"
      quality : "album.ai.embedding.request"
      duplicate : "album.ai.duplicate.request"
      category : "album.ai.category.request"
      aesthetic : "album.ai.aesthetic.request"
      people : "album.ai.people.request"
      style : "album.ai.style.request"
    response:
      embedding: "album.ai.embedding.response"
      quality: "album.ai.embedding.response"
      duplicate: "album.ai.duplicate.response"
      category: "album.ai.category.response"
      aesthetic: "album.ai.aesthetic.response"
      people: "album.ai.people.response"
      style: "album.ai.style.response"