spring:
  # secretmanager import 삭제 — CI/CD에서 env로 주입하므로 불필요
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier

  data:
    redis:
      host: ${REDIS_URL}
      port: 6379

  datasource:
    url:      ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    url:      ${DB_URL}
    user:     ${DB_USER}
    password: ${DB_PASS}

  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME_DEV}

jwt:
  secret: ${JWT_SECRET}

ai:
  server:
    base-url: ${AI_SERVER_URL_DEV}

custom:
  isProd: true
