spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ongi_test}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: ${FLYWAY_URL:jdbc:mysql://localhost:3306/ongi_test}
    user: ${FLYWAY_USER:root}
    password: ${FLYWAY_PASSWORD:root}
    baseline-version: 14
    baseline-on-migrate: true

  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID:test}
      redirect: http://localhost:8080/auth/login/kakao

  cloud:
    gcp:
      secretmanager:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_URL:test}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: be-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:test}
      secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET_NAME:s3-dev-ongi}

jwt:
  secret: ${JWT_SECRET:test_key_it_is_test_not_for_prod_or_dev_you_got-it_?}

ai:
  server:
    base-url: ${AI_SERVER_URL:http://localhost:8081}

logging:
  level:
    org.springframework.boot.context.config: DEBUG

custom:
  isProd: false