spring:
  config:
    import:
      - optional:secretmanager:/       # 루트에 있는 시크릿 모두 로드
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier
      secretmanager:
        enabled: true

  data:
    redis:
      host: ${sm://redis_server_url}    # Secret Manager의 시크릿 ID가 "redis_server_url" 이어야 함
      port: 6379

  datasource:
    url:      ${sm://db_url_dev}
    username: ${sm://db_user_dev}
    password: ${sm://db_password_dev}

  flyway:
    url:      ${sm://db_url_dev}
    user:     ${sm://db_user_dev}
    password: ${sm://db_password_dev}

  kakao:
    auth:
      client: ${sm://kakao_client_id}

cloud:
  aws:
    credentials:
      access-key: ${sm://aws_access_key_id}
      secret-key: ${sm://aws_secret_access_key}
    region:
      static: ${sm://aws_region}
    s3:
      bucket: ${sm://s3_bucket_name_dev}

jwt:
  secret: ${sm://jwt_secret}

ai:
  server:
    base-url: ${sm://ai_server_url_dev}
custom:
  isProd: true
