spring:
  config:
    activate:
      on-profile: local   # 이름은 파일명과 일치해야 함

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ongi}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  flyway:
    url: ${FLYWAY_URL:jdbc:mysql://localhost:3306/ongi}
    user: ${FLYWAY_USER:root}
    password: ${FLYWAY_PASSWORD:root}
    baseline-version: 15
    baseline-on-migrate: true

  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: http://localhost:8080/auth/login/kakao

  cloud:
    gcp:
      secretmanager:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_URL}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: be-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET_NAME:s3-dev-ongi}

jwt:
  secret: ${JWT_SECRET}

ai:
  server:
    base-url: ${AI_SERVER_URL:http://localhost:8081}

custom:
  isProd: false