spring:
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier
      secretmanager:
        enabled: true

  data:
    redis:
      host: ${redis_server_url}
      port: 6379

  kakao:
    auth:
      client: ${kakao-client-id}
      redirect: https://dev.ongi.today/auth/callback/kakao

  datasource:
    url: ${db-url-dev}
    username: ${db-user-dev}
    password: ${db-password-dev}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        type: trace

  sql:
    init:
      mode: never

  flyway:
    url: ${flyway-url-dev}
    user: ${flyway-user-dev}
    password: ${flyway-password-dev}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  aws:
    credentials:
      access-key: ${aws-access-key-id}
      secret-key: ${aws-secret-access-key}
    region:
      static: ${aws-region}
    s3:
      bucket: ${s3-bucket-name-dev}
    stack:
      auto: false

jwt:
  secret: ${jwt-secret}

ai:
  server:
    base-url: ${ai-server-url-dev}

custom:
  isProd: false
