spring:
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier
      secretmanager:
        enabled: true
        secret-names:
          - flyway-url-dev:spring.flyway.url
          - flyway-user-dev:spring.flyway.user
          - flyway-password-dev:spring.flyway.password
          - kakao-client-id:spring.kakao.auth.client
          - db-url-dev:spring.datasource.url
          - db-user-dev:spring.datasource.username
          - db-password-dev:spring.datasource.password
          - redis-server-url:spring.data.redis.host
          - aws-access-key-id:cloud.aws.credentials.access-key
          - aws-secret-access-key:cloud.aws.credentials.secret-key
          - aws-region:cloud.aws.region.static
          - s3-bucket-name-dev:cloud.aws.s3.bucket
          - jwt-secret:jwt.secret
          - ai-server-url-dev:ai.server.base-url

  data:
    redis:
      host: ${spring.data.redis.host}
      port: 6379

  kakao:
    auth:
      client: ${spring.kakao.auth.client}
      redirect: https://dev.ongi.today/auth/callback/kakao

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        type: trace

  sql:
    init:
      mode: never

  flyway:
    url: ${spring.flyway.url}
    user: ${spring.flyway.user}
    password: ${spring.flyway.password}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  aws:
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    region:
      static: ${cloud.aws.region.static}
    s3:
      bucket: ${cloud.aws.s3.bucket}
    stack:
      auto: false

jwt:
  secret: ${jwt.secret}

ai:
  server:
    base-url: ${ai.server.base-url}

custom:
  isProd: false
