spring:
  config:
    import: "optional:secretmanager:/"

  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier
      secretmanager:
        enabled: true

  data:
    redis:
      host: ${redis_server_url}
      port: 6379

  datasource:
    url: ${db_url_dev}
    username: ${db_user_dev}
    password: ${db_password_dev}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  flyway:
    url: ${db_url_dev}
    user: ${db_user_dev}
    password: ${db_password_dev}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kakao:
    auth:
      client: ${kakao_client_id}
      redirect: https://dev.ongi.today/auth/callback/kakao

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: never

cloud:
  aws:
    credentials:
      access-key: ${aws_access_key_id}
      secret-key: ${aws_secret_access_key}
    region:
      static: ${aws_region}
    s3:
      bucket: ${s3_bucket_name_dev}
    stack:
      auto: false

jwt:
  secret: ${jwt_secret}

ai:
  server:
    base-url: ${ai_server_url_dev}

custom:
  isProd: false