spring:
  application:
    name: ongiBE

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    root: INFO
    ongi.ongibe: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG

kafka:
  topic:
    request:
      embedding : "album.ai.embedding.request"
      quality : "album.ai.quality.request"
      duplicate : "album.ai.duplicate.request"
      category : "album.ai.category.request"
      score : "album.ai.score.request"
      people : "album.ai.people.request"
      style : "album.ai.style.request"
    response:
      embedding: "album.ai.embedding.response"
      quality: "album.ai.quality.response"
      duplicate: "album.ai.duplicate.response"
      category: "album.ai.category.response"
      score: "album.ai.score.response"
      people: "album.ai.people.response"
      style: "album.ai.style.response"