spring:
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      secretmanager:
        enabled: true

  data:
    redis:
      host: ${redis_server_url}  # sm:// 제거
      port: 6379

  kakao:
    auth:
      client: ${kakao-client-id}  # sm:// 제거
      redirect: https://dev.ongi.today/auth/callback/kakao

  datasource:
    url: ${db-url-dev}           # sm:// 제거
    username: ${db-user-dev}     # sm:// 제거
    password: ${db-password-dev} # sm:// 제거
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        type: trace

  sql:
    init:
      mode: never

  flyway:
    url: ${flyway-url-dev}         # sm:// 제거
    user: ${flyway-user-dev}       # sm:// 제거
    password: ${flyway-password-dev} # sm:// 제거
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  aws:
    credentials:
      access-key: ${aws-access-key-id}     # sm:// 제거
      secret-key: ${aws-secret-access-key} # sm:// 제거
    region:
      static: ${aws-region}                # sm:// 제거
    s3:
      bucket: ${s3-bucket-name-dev}        # sm:// 제거
    stack:
      auto: false

jwt:
  secret: ${jwt-secret}  # sm:// 제거

ai:
  server:
    base-url: ${ai-server-url-dev}  # sm:// 제거

custom:
  isProd: false