spring:
  application:
    name: ongiBE

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

logging:
  level:
    root: INFO
    ongi.ongibe: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG