spring:
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_SERVER_URL}
      port: 6379

  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: https://dev.ongi.today/auth/callback/kakao

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        type: trace

  sql:
    init:
      mode: never

  flyway:
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET}

ai:
  server:
    base-url: ${AI_SERVER_URL}

custom:
  isProd: false
