spring:
  threads:
    virtual:
      enabled: true

  cloud:
    gcp:
      project-id: dev-ongi-3-tier
      secretmanager:
        enabled: true
        secret-names:
          - flyway-url-dev:spring.flyway.url
          - flyway-user-dev:spring.flyway.user
          - flyway-password-dev:spring.flyway.password
          - kakao-client-id:spring.kakao.auth.client
          - db-url-dev:spring.datasource.url
          - db-user-dev:spring.datasource.username
          - db-password-dev:spring.datasource.password
          - aws-access-key-id:cloud.aws.credentials.access-key
          - aws-secret-access-key:cloud.aws.credentials.secret-key
          - aws-region:cloud.aws.region.static
          - s3-bucket-name-dev:cloud.aws.s3.bucket
          - jwt-secret:jwt.secret
          - ai-server-url-dev:ai.server.base-url

  data:
    redis:
      host: ${redis_server_url}
      port: 6379

  kakao:
    auth:
      client: placeholder-will-be-replaced-by-secret
      redirect: https://dev.ongi.today/auth/callback/kakao

  datasource:
    url: placeholder-will-be-replaced-by-secret
    username: placeholder-will-be-replaced-by-secret
    password: placeholder-will-be-replaced-by-secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      leak-detection-threshold: 30000
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        type: trace

  sql:
    init:
      mode: never

  flyway:
    url: placeholder-will-be-replaced-by-secret
    user: placeholder-will-be-replaced-by-secret
    password: placeholder-will-be-replaced-by-secret
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  aws:
    credentials:
      access-key: placeholder-will-be-replaced-by-secret
      secret-key: placeholder-will-be-replaced-by-secret
    region:
      static: placeholder-will-be-replaced-by-secret
    s3:
      bucket: placeholder-will-be-replaced-by-secret
    stack:
      auto: false

jwt:
  secret: placeholder-will-be-replaced-by-secret

ai:
  server:
    base-url: placeholder-will-be-replaced-by-secret

custom:
  isProd: false